# -*- coding: utf-8 -*-
"""迁移 Windows MySQL cs_biz_db → 生成 compose mysql 初始化 SQL"""
import pymysql, io, os

conn = pymysql.connect(host='127.0.0.1', port=3306, user='root', password='123456',
                       charset='utf8mb4', connect_timeout=5)
cur = conn.cursor()
cur.execute("USE cs_biz_db")
buf = io.StringIO()
buf.write("-- Auto-generated by deploy/dump_mysql.py (from Windows MySQL cs_biz_db)\n")
buf.write("SET NAMES utf8mb4;\n")

for t in ['messages', 'orders', 'tickets']:
    cur.execute("SHOW CREATE TABLE `%s`" % t)
    buf.write(cur.fetchone()[1] + ";\n\n")
    cur.execute("SELECT * FROM `%s`" % t)
    cols = [d[0] for d in cur.description]
    for r in cur.fetchall():
        vals = []
        for v in r:
            if v is None:
                vals.append("NULL")
            elif isinstance(v, (int, float)):
                vals.append(str(v))
            else:
                vals.append("'" + str(v).replace("\\", "\\\\").replace("'", "''") + "'")
        buf.write("INSERT INTO `%s` (%s) VALUES (%s);\n" % (t, ",".join("`%s`" % c for c in cols), ",".join(vals)))
    buf.write("\n")
conn.close()

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'sql/mysql', 'init.sql')
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, 'w', encoding='utf8') as f:
    f.write(buf.getvalue())
print('init.sql 已生成:', out, os.path.getsize(out), 'bytes')
